logLevel: info

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 5
        Log_Level debug
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        Trace_Error On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*expense*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [INPUT]
        Name tail
        Path /var/log/containers/*ingress-nginx-controller*.log
        Parser nginx_parser
        Tag nginx.*

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size False
        K8S-Logging.Parser On

    [FILTER]
        Name parser
        Match nginx.*
        Key_Name log
        Parser nginx_parser
        Preserve_Key On
        Reserve_Data On
        Parser nginx_ingress_parser

  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Index fluent-bit
        Type  _doc
        Host elasticsearch-master
        Port 9200
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix logstash
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match host.*
        Index fluent-bit
        Type  _doc
        Host elasticsearch-master
        Port 9200
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match expense-app-dep-*
        Index fluent-bit
        Type  _doc
        Host elasticsearch-master
        Port 9200
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix expense
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match nginx.*
        Index fluent-bit-nginx
        Type  _doc
        Host elasticsearch-master
        Port 9200
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix nginx
        Retry_Limit False
        Suppress_Type_Name On

  customParsers: |
   [PARSER]
    Name        nginx_parser
    Format      regex
    Regex       ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
    Name        nginx_ingress_parser
    Format      regex
    Regex       ^(?<host>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (\[(?<proxy_alternative_upstream_name>[^ ]*)\] )?(?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<req_id>[^ ]*)$
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z