logLevel: info

config:
  service: |
    [SERVICE]
                Daemon Off
                Flush {{ .Values.flush }}
                Log_Level debug
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port {{ .Values.metricsPort }}
                Health_Check On
                Trace_Error On

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/rando*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On
            
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd elastic
                tls On
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix logstash
                Retry_Limit False
                Suppress_Type_Name On

            [OUTPUT]
                Name es
                Match host.*
                Index fluent-bit
                Type  _doc
                Host elasticsearch-master
                Port 9200
                HTTP_User elastic
                HTTP_Passwd elastic
                tls On
                tls.verify Off
                Logstash_Format On
                Logstash_Prefix node
                Retry_Limit False
                Suppress_Type_Name On