apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "horsing-around.fullname" . }}-config
  labels:
    {{- include "horsing-around.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.configMap.logLevel | quote }}
  PERSISTENCE: {{ .Values.configMap.persistence | quote }}