apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "horsing-around.fullname" . }}
  labels:
    {{- include "horsing-around.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "horsing-around.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "horsing-around.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "horsing-around.fullname" . }}-secret
                key: mongodb-root-password
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "horsing-around.fullname" . }}-secret
                key: mongodb-username
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ include "horsing-around.fullname" . }}-secret
                key: mongodb-database
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: {{ include "horsing-around.fullname" . }}-secret
                key: mongodb-uri
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ include "horsing-around.fullname" . }}-config
        resources:
          {{- toYaml .Values.resources | nindent 12 }}