apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{ toYaml .Values.app.labels | indent 4  }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{ toYaml .Values.app.labels | indent 4  }}
  template:
    metadata:
      labels: 
        {{ toYaml .Values.app.labels | indent 4  }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.deployment.image.repository }}:{{.Values.deployment.image.tag}}"
          ports:
          - containerPort: {{ .Values.app.port }}
    env:
      - name: MONGODB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: horsing-around-secret
            key: mongodb-root-password
      - name: MONGODB_USERNAME
        valueFrom:
          secretKeyRef:
            name: horsing-around-secret
            key: mongodb-username
      - name: MONGODB_DATABASE
        valueFrom:
          secretKeyRef:
            name: horsing-around-secret
            key: mongodb-database
      - name: MONGODB_URI
        valueFrom:
          secretKeyRef:
            name: horsing-around-secret
            key: mongodb-uri
          envFrom:
            # - secretRef: 
            #     name: {{ .Values.secret.name }}
            - configMapRef:
                name: {{ .Values.configMap.name }}