apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "horsing-around.fullname" . }}
  labels:
    {{- include "horsing-around.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "horsing-around.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "horsing-around.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "horsing-around.fullname" . }}-config