apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
  - port: metrics
    targetPort: 5000
    path: /metrics