apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{ toYaml .Values.app.labels | indent 4  }}
    release: prometheus 
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.app.labels | indent 4  }}
  endpoints:
  - port: 80-5000  
    targetPort: 5000
    path: /metrics
