apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- with .Values.app.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  endpoints:
  - port: metrics
    path: /metrics