apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{ toYaml .Values.app.labels | indent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{ toYaml .Values.app.labels | indent 6 }}
  endpoints:
  - port: metrics
    path: /metrics