app:
  name: "horsing-around"
  port: 5000
  isMongo: true
  labels:
    app: horsing-around

deployment:
  replicas: 2
  image:
    repository: 644435390668.dkr.ecr.us-east-1.amazonaws.com/carmit-portfolio
    pullPolicy: IfNotPresent
    tag: latest

service:
  name: horsing-around-service
  type: ClusterIP
  port: 80
  metricsPort: 5000

configMap:
  name: horsing-around-conf
  data:
    PERSISTENCE: "false"
    LOG_LEVEL: "debug"

secret:
  name: horsing-around-mongodb
  type: Opaque

ingress:
  enabled: true
  name: horsing-around-ingress
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: horsing-around.zapto.org
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - secretName: horsing-around-cert
      hosts:
        - horsing-around.zapto.org

mongodb:
  architecture: replicaset 
  replicaCount: 2 
  auth:
    enabled: true
    existingSecret: horsing-around-mongodb
    rootPasswordKey: mongodb-root-password
    userPasswordKey: mongodb-passwords
    username: root
    database: admin
  persistence:
    enabled: true
    size: 3Gi
    storageClass: "gp2"
  global:
    storageClass: "gp2"
  service:
    name: horsing-around-mongodb-headless