apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carmit-crm-tls
  namespace: horsing-around
spec:
  secretName: carmit-crm-tls-xsb92
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: carmit-crm.zapto.org
  dnsNames:
    - carmit-crm.zapto.org