apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: horsing-around-cert
spec:
  secretName: horsing-around-cert
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - carmit-crm.zapto.org