apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef: 
    name: cluster-issuer-prod
    kind: ClusterIssuer
  dnsNames:
    - carmit-crm.zapto.org