apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-install-crds
  namespace: cert-manager
  annotations:
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/sync-wave": "0"
spec:
  template:
    spec:
      containers:
      - name: install-crds
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
          - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.12.0/cert-manager.crds.yaml
      restartPolicy: Never

