apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:CarmitHaas/gitops-HA.git'
    targetRevision: HEAD
    path: logging/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true