apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd 
spec: 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      valuesObject:
        secret:
          password: "elastic"
        replicas: 2  
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
          volumeClaimTemplate:
            resources:
              requests:
                storage: 3Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true