apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "horsing-around-app.fullname" . }}-config
  labels:
    {{- include "horsing-around-app.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.config.SECRET_KEY }}