# Elasticsearch values
elasticsearch:
  replicas: 1  # Reduced from 2 to 1
  minimumMasterNodes: 1
  persistence:
    enabled: true
    labels:
      enabled: true
  
  # Add resource limits and requests
  resources:
    requests:
      cpu: "100m"  # Request 0.1 CPU cores
      memory: "512Mi"  # Request 512MB of memory
    limits:
      cpu: "500m"  # Limit to 0.5 CPU cores
      memory: "1Gi"  # Limit to 1GB of memory

  # Adjust Java heap size
  esJavaOpts: "-Xmx512m -Xms512m"

  # Disable features you might not need
  xpack.security.enabled: false
  xpack.monitoring.enabled: false

  # Configure smaller disk size if needed
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5Gi 
  
# Kibana values
kibana:
  ingress:
    enabled: true
    className: "nginx"
    pathtype: ImplementationSpecific
    hosts:
      - host: carmit-crm.zapto.org
        paths:
          - path: /kibana
    tls:
      - hosts:
          - carmit-crm.zapto.org
        # secretName: 

# Fluent-bit values
fluent-bit:
  flush: 1
  metricsPort: 2020 
  logLevel: info
  
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*horse*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix poster
          Retry_Limit False

      [OUTPUT]
          Name es
          Match host.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False

    # customParsers: |
    #   [PARSER]
    #       Name json_parser
    #       Format regex
    #       Regex ^[^\s]+\s+[^\s]+\s+[^\s]+\s+(?<json>{.*})
    #       Time_Key asctime
    #       Time_Format %Y-%m-%d %H:%M:%S,%L
    #       Time_Keep On
    #       Decode_Field_As json json