# Horsing Around specific values
replicaCount: 3

image:
  repository: 644435390668.dkr.ecr.us-east-1.amazonaws.com/carmit-portfolio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: #your host here
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - #your host here
      secretName: #your secretName here

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

configMap:
  logLevel: info
  persistence: "true"

# MongoDB specific values
mongodb:
  auth:
    rootPassword: #your password here
    username: root
    database: admin
  architecture: replicaset
  replicaCount: 3
